on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:focal
    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run: | 
          apt-get update && apt-get install -y python3-pip
          pip3 install -r requirements.txt
          python -m playwright install

      - name: run
        run: python main.py
        env:
          BOT_ID: ${{ secrets.BOT_ID }}

      - name: save
        continue-on-error: true
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add jongraz.json
          git commit -m db_update
          git push
